<a href="https://colab.research.google.com/github/varmatilak22/learning_tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>





##  In This notebook , we're going some of the most fundamental concepts of tensors using tensorflow

More Specifically ,we're going to cover :
* Introduction to tensors
*Getting some information from tensors
*Manipulating tensors
*tensors and NumPy
*Using ATFP function (a way to speed up regular python functions)
*Using GPUs with tensorflow (or TPUs)
*Exercises to try for yourself!


## Introduction to Tensors

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
#create tensors with tf constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the number of dimensions of a tensor (ndim stands for n dimensional array)
scalar.ndim

0

In [ ]:


#cREATE  a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Check the dimension of our vector
vector.ndim

1

In [ ]:


#create a matrix (has more than 1 dimension)
matrix=tf.constant([[10,10],[10,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [10, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,6.],
                              [8.,9.]],dtype=tf.float16) #Specify the datatype with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  6.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#What is dimension of another_matrix
another_matrix.ndim

2

In [ ]:

scalar.ndim,vector.ndim,matrix.ndim,another_matrix.ndim

(0, 1, 2, 2)

In [ ]:
#Let' create a tensor
tensor= tf.constant([[[[10.,7.],[9.,8.]],
                      [[10.,9.],[20.,20.]]],[[[10.,7.],[9.,8.]],
                      [[10.,9.],[20.,20.]]]],dtype=tf.float16
                    )

In [ ]:
tensor.dtype

tf.float16

In [ ]:
response_mat=tf.random.uniform(shape=(4,8),minval=2,maxval=20,dtype=tf.int32)

In [ ]:


response_mat

<tf.Tensor: shape=(4, 8), dtype=int32, numpy=
array([[ 2,  3,  6,  6,  5, 15,  8, 10],
       [19, 19,  4, 18, 19, 19, 19, 12],
       [11, 14,  7, 18,  3,  3,  3,  9],
       [19, 13,  5,  5, 15, 12, 14,  4]], dtype=int32)>




## Day-2
### Creating tensor with "tf.variable"


In [ ]:
import tensorflow as tf
Changeable_tensor=tf.Variable([10,7])
unChangeable_tensor=tf.constant([10,7])
Changeable_tensor,unChangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:

Changeable_tensor[0]=7

TypeError: ignored

In [ ]:
# How about we try .assign()
Changeable_tensor[0].assign(9)

In [ ]:
#Lets try change our unchangebale tensor
Changeable_tensor[0].assign(7)

###Creating random tensors
Random tensors are tensors of some arbitary size which contain random numbers.


In [ ]:

#create 2 random tensors
rand1=tf.random.uniform(shape=(3,4),minval=10,maxval=100,dtype=tf.int32)
rand2=tf.random.uniform(shape=(4,3),minval=1,maxval=50,dtype=tf.int32)
rand1,rand2

In [ ]:
random_1=tf.random.Generator.from_seed(7)#set seed for reproduciblity
random_1=random_1.normal(shape=(3,2))
random_1


In [ ]:
random_2=tf.random.Generator.from_seed(7)
random_2=random_2.normal(shape=(3,2))
random_2

In [ ]:
#Are random_1 and random_2 are equal=yes
random_1,random_2

##yes

In [ ]:
random_1,random_2,random_1==random_2



### Shuffle the order of elements in a tensor

#shuffle a tensor (valuable for when you want to shuffle your data so the inherent order does'nt effect learning)

In [ ]:
not_shuffled=tf.constant([[10,7],
                         [4,6],
                         [2,5]])
not_shuffled

###shuffled our non-shuffled tensor

In [ ]:
tf.random.set_seed(5)
shuffled=tf.random.shuffle(not_shuffled)
shuffled,not_shuffled

In [ ]:
# tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=(2))

⚒** Exercise:** Read through tensorflow documentation on random 5random tensors

###Creating 5 random tensors for practice

In [ ]:
random_1=tf.constant([[1,2,3],
                      [3,4,5],
                      [5,6,7],
                      [7,8,9]])
#Without random seed (no global and operation seed)
shuf_1=tf.random.shuffle(random_1)
shuf_1

In [ ]:
#Shuffle with using global level seed
tf.random.set_seed(10)
shuf_2=tf.random.shuffle(random_1)
shuf_2

In [ ]:
#shuffled with operation level seed with no global level seed
shuf_3=tf.random.shuffle(random_1,seed=(2))
shuf_3

In [ ]:

#shuffled with both operation and global level seed
tf.random.set_seed(20)
shuf_4=tf.random.shuffle(random_1,seed=(10))
shuf_4

In [ ]:
shuf_4=tf.random.shuffle(tf.range(1,20))
tf.random.set_seed(10)

In [ ]:
tf.random.set_seed(10)
shuf_5=tf.random.shuffle(tf.range(1,20))
shuf_5

In [ ]:
shuf_6=tf.random.shuffle(tf.range(1,20),seed=(20))
shuf_6

In [ ]:
shuf_4,shuf_5,shuf_6

In [ ]:
tf.random.set_seed(42) #Global level random seed
tf.random.shuffle(not_shuffled,seed=42) #operation level random seed

### It looks like if we want our tensors may be shuffled tensors in the same order,we've got to use global level random seed as well as operation level random seed as well as the operation level random seed:
##Rule 4:
### If both the global and operation seed are set:Both seeds are used in conjuction to determine the random sequence.

##Other ways to make tensors

In [ ]:





#create tensor of all ones
tf.ones([10,8])

In [ ]:





#create a tensor of all zeroes
tf.zeros([3,5])

### Turn NumPy arrays into tensorflow tensors is that tensors can be run on a GPU(much faster for numerical computing).


In [ ]:
#You can also turn NumPy arrays into tensors
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32) #create a NumPy array between 1 and 25
numpy_A

# x=tf.constant(some_matrix) # capital for matrix or tensor
# y=tf.constant(vector) # non-captial vector

In [ ]:
A=tf.constant(numpy_A,shape=(6,4))
A

In [ ]:
B=tf.constant(numpy_A,shape=(2,3,4))
B

In [ ]:
A,B

In [ ]:
C=tf.constant(numpy_A,shape=(12,2))
D=tf.constant(numpy_A,shape=(8,3))
A,B,C,D

In [ ]:
E=tf.constant(numpy_A,shape=(2,3,2,2))
E.ndim # 4D tensor using 1D numpy array

### Getting information from tensors
When dealing with tenors you probably want to be aware of the following attributes:
1.   Shape
2.   Rank
3.  Axis and dimension
4.  size



In [ ]:
#create a rank 4 tensor (4D)
rank_4_tensor=tf.zeros([2,3,4,5])
rank_4_tensor

In [ ]:
rank_4_tensor[0,1,2,4]

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

In [ ]:
#Get different attributes of our tensor
print("Datatype of every element:",rank_4_tensor.dtype)

In [ ]:
  print("Numbe of dimensions(rank):",rank_4_tensor.ndim)

In [ ]:
print("Shape of Tensor:",rank_4_tensor.shape)
print("Size of tensor:",tf.size(rank_4_tensor))

In [ ]:
print("Elements along 0 axis:",rank_4_tensor.shape[0])
print("Elements along the last axis:",rank_4_tensor.shape[-1])
print("total number of elements in our tensors:",tf.size(rank_4_tensor))
print("total number of elements in our numpy array:",tf.size(rank_4_tensor).numpy())

### Indexing tensors

Tensors can be indexed just like Python lists.

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

In [ ]:
#Get each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1]

In [ ]:
rank_4_tensor[:1,:1,:1,:2]

In [ ]:
rank_4_tensor[:1,:1,:,:1]

In [ ]:
rank_4_tensor[:,:1,:1,:1]

In [ ]:
rank_4_tensor[:1,:,:1,:1]

In [ ]:
rank_4_tensor[:1,:1,:,:1]

In [ ]:
rank_4_tensor[:1,:1,:1,:]

In [ ]:
#Create a rank 2 tensor (2D)
rank_2_tensor=tf.constant([[10,7],[4,2]])
rank_2_tensor

In [ ]:
rank_2_tensor.shape,rank_2_tensor.ndim

In [ ]:
#get the last item of each row of our rank 2 tensor
rank_2_tensor[:,-1]

In [ ]:
#Add in extra dimension to our rank 2 tensor
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

In [ ]:
#Other alternatives tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) #-1 means expand the final axis

In [ ]:
tf.expand_dims(rank_4_tensor,axis=0)

In [ ]:

tf.expand_dims(rank_2_tensor,axis=1) #Axis is 1

In [ ]:
tf.expand_dims(rank_2_tensor,axis=2)

In [ ]:
tf.expand_dims(rank_2_tensor,axis=-1)

### Manipulating tensors (tensor operations)
**Basic operations**

`+`:Addition

`-`:Subtraction

`*`:Multiplication

`/`:Division

`**`:Exponent

`//`:Floor Division




In [ ]:
# You can add values to a tensor using the addition operator
tensor=tf.constant([[10,7],[3,4]])
tensor

In [ ]:
tensor+10,tensor-10,tensor*10,tensor/10 #implict datatype conversion from int32 to float32

In [ ]:
 #Original tensor is unchanged
tensor_1=tensor+10

In [ ]:
tensor_1

In [ ]:
tensor_2=(tensor-10).numpy()
tensor_3=tensor*10
tensor_4=tensor/10
tensor_5=tensor//10
tensor_5=tensor**2

In [ ]:

tensor_2,tensor_3,tensor_4,tensor_5

In [ ]:
# We can use the tensorflow built-in function too
tf.multiply(tensor,10)

**Matrix Multiplication**

In machine learning matrix multipication is one of the most common tensor operation.

There 2 rules our tensors (or matrices) need to fulfil if we're going to matrix mutliply them:

1.The inner dimensions must watch

2.The Resulting matrix has the shape of the Outer dimensions.

In [ ]:
#Matrix multipication in tensorflow
import tensorflow as tf
import numpy as np

In [ ]:


tensor_1=tf.constant([[10,7],
                      [4,5]])
tensor_1

In [ ]:

num_A=np.arange(10)
num_A
tensor_2=tf.constant(num_A,shape=(2,5))

In [ ]:
tensor_2=tf.cast(tensor_2,tf.int32)

In [ ]:
tf.matmul(tensor_1,tensor_1)

In [ ]:
tf.matmul(tensor_1,tensor_2)

In [ ]:
tf.random.set_seed(42)
tensor_3 = tf.random.uniform(shape=(2, 3, 4), minval=0, maxval=24, dtype = tf.int32)
# tf.random.set_seed(42)
# tensor_3 = tf.random.uniform(shape=(2, 3, 4), minval=0, maxval=24, dtype=tf.int32)
tensor_3

In [ ]:
tf.random.set_seed(20)
tensor_4=tf.random.uniform(shape=(2,4,5),minval=24,maxval=64,dtype=tf.int32)
tensor_4

In [ ]:
tf.matmul(tensor_3,tensor_4)

In [ ]:
#Matrix multilication usinh python operator "@"
tensor_1*tensor_1

In [ ]:
tensor_1@tensor_2

In [ ]:
tensor_1.shape,tensor_2.shape

In [ ]:
#create tensor of (3,2) tensor
X=tf.constant([[1,3],
                [4,3],
                [5,6]])
#create tensor of (3,2) tensor
Y=tf.constant([[7,8],
               [9,10],
               [11,12]])

X,Y

📑 **Resource** Info and example of matrix multiplication: https://www.mathsisfun.com/algebra/matrix-mutliplying.html

In [ ]:
#Try to matrix multiply tensors of same shape
Y=tf.reshape(Y,(2,3))

In [ ]:
Y

In [ ]:
X,Y

In [ ]:
X@Y

In [ ]:
tf.matmul(X,Y)

In [ ]:
#Lets code
Z=tf.constant([[1,2,4],
               [3,5,6],
               [7,8,9]])
Z

In [ ]:
W=tf.constant([[2,3],
               [4,5],
               [6,7]])
W

In [ ]:


Z,W

In [ ]:

tf.matmul(Z,W)

In [ ]:






#Try to multiply tf.reshape
X,Y

In [ ]:
tf.reshape(X,(2,3))@tf.reshape(Y,shape=(3,2))

In [ ]:
tf.matmul(tf.reshape(X,shape=(2,3)),tf.reshape(Y,shape=(3,2)))

In [ ]:
X,Y,X*tf.reshape(Y,(3,2)),X@Y

In [ ]:
#try change the shape of X instead Y
X,Y

In [ ]:
X.shape,Y.shape

In [ ]:

#Can do the same with transpose
tf.transpose(X),Y

In [ ]:
Z,W

In [ ]:
tensor_3,tensor_4

In [ ]:
tf.transpose(tensor_3),tensor_3

In [ ]:
tf.transpose(tensor_4),tensor_4

In [ ]:
#try matrix multiplication with transpose rather than reshape
Z,W

In [ ]:


Y=tf.transpose(Y)

In [ ]:
X,Y

In [ ]:
tf.matmul(tf.transpose(X),Y)

In [ ]:
tf.matmul(X,tf.transpose(Y))

In [ ]:
X@ tf.transpose(Y)

In [ ]:
print("Transpose :",tf.transpose(X) @ Y)
print("Reshape :",tf.reshape(X,(2,3))@ Y)

In [ ]:

X,tf.transpose(X),tf.reshape(X,(2,3))

**Dot Product**

The matrix multiplication is also refer to as dot product.
You can perform matrix multiplication using:

* `tf.matmul()`
* `tf.tensordot()`

In [ ]:
# Perform the dot perform on X and Y (require X or Y to be transposed)
tf.tensordot(tf.transpose(X),Y,axes=1)

In [ ]:
#Prform matrix mulitplication between X and Y (transpose)
tf.tensordot(X,tf.transpose(Y),axes=1),tf.matmul(X,tf.transpose(Y)),X @ tf.transpose(Y)

In [ ]:
tf.matmul(X,tf.transpose(Y))

In [ ]:

tf.tensordot(X,tf.transpose(Y),axes=1),tf.matmul(X,tf.transpose(Y)),tf.matmul(X,tf.reshape(Y,(2,3)))

In [ ]:
#Check the value of Y ,reshape of Y,transpose of Y
print("Normal Y:")
print(Y,"\n") # "\n" is for next line

print("Y is reshaped to (2,3):")
print(tf.reshape(Y,shape=(2,3)),"\n")


In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
num_A=np.arange(40)
num_A

In [ ]:
tf.random.set_seed(42)
shuffle_1=tf.random.shuffle(num_A)

In [ ]:
tf.random.set_seed(20)
shuffle_2=tf.random.shuffle(num_A)

In [ ]:
shuffle_2

In [ ]:
X=tf.constant(shuffle_2,shape=(2,4,5))
Y=tf.constant(shuffle_1,shape=(2,4,5))
X,Y

In [ ]:
#check the values of Y and reshape Y and transpose Y
print("Normal Y:")
print(Y,"\n")

print("Y reshaped to (2,5,4):")
print(tf.reshape(Y,(2,5,4)),"\n")

print("Y transposed:")
print(tf.transpose(Y))

In [ ]:
tf.matmul(X,tf.reshape(Y,(2,5,4)))

Generally, when performing matrix multplication on two tensor and one of the axes doesn't line up,you will transpose(rather than reshape ) one of the tensors to get satisfy the matrix multiplication rules.

### Changing the Datatype of tensors

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7,2.8,7.4])
B.dtype


In [ ]:
A=tf.constant([[0.455555344484534957465974,0.4734637423648374],
                [0.455555344484534957465974,0.4734637423648374]])
A.dtype

### tf.cast to change dtype of tensor

In [ ]:
tf.cast(B,tf.int32)

In [ ]:
tf.cast(B,tf.float64),tf.cast(A,tf.int8)

In [ ]:
tf.cast(B,tf.uint8)

In [ ]:
tf.__version__

In [ ]:
#Change from float 32 to float64 increasing precision
tf.cast(B,tf.float64)

In [ ]:
#Change from float32 to float16 (reduced precision)
tf.cast(B,tf.float16)

In [ ]:
 B=tf.cast(B,dtype=tf.float16)

In [ ]:
B

In [ ]:
#Change from int32 to float32
E=tf.cast(A,dtype=tf.float32)
A=tf.cast(A,dtype=tf.int32)

In [ ]:
E,A

In [ ]:
E_float16=tf.cast(E,dtype=tf.float16)
E_float16

### Aggregating tensors

Aggregating tensors=condensing them from multiple values down to a smaller amount of values.


In [ ]:
#Get the absolute values
D=tf.constant([-7,-11])
D

In [ ]:
#Get the aboslute values
tf.abs(D)

Lets go to more ways of aggregation:

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor


   

In [ ]:
#Create a tensor
F=tf.constant(np.arange(24),shape=(2,3,4))

NameError: ignored

In [ ]:
#Adding global level seed
tf.random.set_seed(42)
F=tf.random.shuffle(F)

In [ ]:
#Shufflig each and every element of 3d tensor by  flaatening tensor
F=tf.reshape(F,shape=(24))

InvalidArgumentError: ignored

In [ ]:
#Shuffling flattened 3d tensor
tf.random.set_seed(42)
F=tf.random.shuffle(F)

In [ ]:
F=tf.reshape(F,shape=(2,3,4))

InvalidArgumentError: ignored

In [ ]:
F

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.8, 9.1, 1.7, 2.5], dtype=float32)>

### Getting maximum element of the tensor
**tf.reduce_max()**

In [ ]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=9.1>

In [ ]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=1.7>

In [ ]:
tf.reduce_mean(F)

<tf.Tensor: shape=(), dtype=float32, numpy=5.025>

In [ ]:
tf.reduce_sum(F)

<tf.Tensor: shape=(), dtype=float32, numpy=20.1>

In [ ]:
F=tf.cast(F,tf.float32)

In [ ]:
F

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.8, 9.1, 1.7, 2.5], dtype=float32)>

In [ ]:
#All aggrgate functions in float Style
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=1.7>

In [ ]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=9.1>

In [ ]:
tf.reduce_sum(F)

<tf.Tensor: shape=(), dtype=float32, numpy=20.1>

In [ ]:
tf.reduce_mean(F)

<tf.Tensor: shape=(), dtype=float32, numpy=5.025>

In [ ]:
#Creating a random tensor with large tensor
E=tf.constant(np.random.randint(low=0,high=100))
E


NameError: ignored

In [ ]:
tf.shape(E)

In [ ]:
E=tf.reshape(E,shape=(2,5,5))

NameError: ignored

In [ ]:
E

NameError: ignored

In [ ]:
tf.reduce_min(E)

NameError: ignored

In [ ]:
tf.reduce_max(E)

NameError: ignored

In [ ]:
tf.reduce_sum(E)

NameError: ignored

In [ ]:
tf.reduce_mean(E)

NameError: ignored

⚒ **Execrise** With what we have learn ,find the variance and standard deviation of our E tensor using TensorFlow methods.

In [ ]:
#Typecasting in E from int32 to float32 as variance method only takes real or complex inputs
E=tf.cast(E,tf.float32)

NameError: ignored

In [ ]:
#Tensorflow method of finding tensors
tf.math.reduce_variance(E)

In [ ]:
#Standard deviation of E
tf.math.reduce_std(E)

In [ ]:
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np

In [ ]:
E=tf.constant(np.random.randint(100,size=(3,4)))

In [ ]:
tf.random.set_seed(42)
E

<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
array([[99, 23, 17, 71],
       [12, 67, 93, 20],
       [ 0, 57, 82, 92]])>

In [ ]:
E

<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
array([[99, 23, 17, 71],
       [12, 67, 93, 20],
       [ 0, 57, 82, 92]])>

In [ ]:
tfp.stats.variance(E)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1946,  354, 1124,  914])>

In [ ]:
# convert to float 64
E=tf.cast(E,dtype=tf.float64)

In [ ]:
E

<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[99., 23., 17., 71.],
       [12., 67., 93., 20.],
       [ 0., 57., 82., 92.]])>

In [ ]:
tfp.stats.variance(E)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1946.        ,  354.66666667, 1124.66666667,  914.        ])>

## Aggregating tensors

In [ ]:
F=tf.constant([1.7,2.5,6.8,9.1])
F

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.7, 2.5, 6.8, 9.1], dtype=float32)>

## Aggregating tensors

Aggregating tensors=condensing them from multiple values down to a smaller amount of values.

In [ ]:
## Getting the absolute values
D=tf.constant([-7,-8,-5,-2])
D

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-7, -8, -5, -2], dtype=int32)>

In [ ]:
#Getting absolute values
tf.abs(D)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([7, 8, 5, 2], dtype=int32)>

Lets go through few versions of aggregation

* Get the minimum
* Get the maximum
* Get the sum
* Get the mean


In [ ]:
# Creating a random tensor with a large values between 0 and 100 ofsize of 50
import numpy as np
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([41, 61, 94, 32, 79, 20, 53, 76, 76, 88, 85, 56, 74, 39, 51, 29, 33,
       72, 12, 56, 26, 19, 71, 47,  2, 63, 85, 60, 10, 60, 72, 82, 90, 14,
       43, 10,  7, 10, 39, 41, 80, 71,  8, 51, 99, 53, 37, 65, 50,  3])>

In [ ]:
#Size of tensor
tf.size(E),E.ndim,E.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, 1, TensorShape([50]))

In [ ]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2495>

In [ ]:
tf.math.reduce_std(E)

TypeError: ignored

In [ ]:
# We have to convert tensorflow dtype into complex and real numbers
E=tf.cast(E,dtype=tf.float32)

In [ ]:
#Variance in tensorflow is one of aggregate functions
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=739.37006>

In [ ]:
#Standard deviation is one of tensorflow functions
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float32, numpy=27.19136>

⚒ **Execrise** Find standard deviation and variance of E Array

In [ ]:
#Standard Deviation
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float32, numpy=27.19136>

In [ ]:
#Variance
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=739.37006>

In [ ]:
#Yes above is my method
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=739.37006>

In [ ]:
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=739.37006>

In [ ]:
#Find the standard deviation
tf.math.reduce_std(E)  #Standard deviation has same method.

<tf.Tensor: shape=(), dtype=float32, numpy=27.19136>

###Find the positional maximum and minimum.

**tf.argmax()** - Function is used to get position of maximum value.

**tf.argmin()** - Function is used to get position of minimum values.

In [ ]:
tf.argmax(E),E

(<tf.Tensor: shape=(), dtype=int64, numpy=44>,
 <tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([41., 61., 94., 32., 79., 20., 53., 76., 76., 88., 85., 56., 74.,
        39., 51., 29., 33., 72., 12., 56., 26., 19., 71., 47.,  2., 63.,
        85., 60., 10., 60., 72., 82., 90., 14., 43., 10.,  7., 10., 39.,
        41., 80., 71.,  8., 51., 99., 53., 37., 65., 50.,  3.],
       dtype=float32)>)

In [ ]:
tf.argmin(E),E

(<tf.Tensor: shape=(), dtype=int64, numpy=24>,
 <tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([41., 61., 94., 32., 79., 20., 53., 76., 76., 88., 85., 56., 74.,
        39., 51., 29., 33., 72., 12., 56., 26., 19., 71., 47.,  2., 63.,
        85., 60., 10., 60., 72., 82., 90., 14., 43., 10.,  7., 10., 39.,
        41., 80., 71.,  8., 51., 99., 53., 37., 65., 50.,  3.],
       dtype=float32)>)

In [ ]:
#Find the positional maximum and minimum
tf.random.set_seed(42)
F=tf.constant(np.random.randint(0,100,size=50))

In [ ]:
F=tf.cast(F,dtype=tf.float32)

In [ ]:
#All aggrgate functions of format tf.reduce_operation(tensor)
tf.reduce_max(F),tf.reduce_min(F),tf.reduce_mean(F),tf.reduce_sum(F)

(<tf.Tensor: shape=(), dtype=float32, numpy=96.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=47.38>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2369.0>)

In [ ]:
#What about variance and standard deviation
tf.math.reduce_variance(F)

<tf.Tensor: shape=(), dtype=float32, numpy=723.75555>

In [ ]:
#Standard deviation
tf.math.reduce_std(F)

<tf.Tensor: shape=(), dtype=float32, numpy=26.902706>

### Find the positional maximum and minimum

In [ ]:
#create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
G=tf.random.uniform(shape=[50])
G

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#Find the positional maximum
tf.argmax(G)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
#Index on our largest value position
G[tf.argmax(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Find the maximum value of G
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Check the equality
assert G[tf.argmax(G)]==tf.reduce_max(G)

In [ ]:
# Find the positional minimum
tf.argmin(G),G

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>)

In [ ]:
#Checking equality of minimum values
G[tf.argmin(G)]==tf.reduce_min(G)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor (removing all single dimensions)

In [ ]:
#Create a tensor to get started
tf.random.set_seed(42)
H=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))

In [ ]:
H

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
H.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
tf.reshape(H,(2,5,5))

<tf.Tensor: shape=(2, 5, 5), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041],
        [0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686],
        [0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ],
        [0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ],
        [0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ]],

       [[0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173],
        [0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ],
        [0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ],
        [0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943],
        [0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]],
      dtype=float32)>

In [ ]:
H_squeezed=tf.squeeze(H)

In [ ]:
H_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### One-Hot Encoding Tensors

In [ ]:
#create a list of indices
some_list=[0,1,2,3] #could be red green blue purple

#One-hot encode our list of indices
tf.one_hot(some_list,depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#Specify custom values for one hot encoding
tf.one_hot(some_list,depth=4,on_value="Yo, I love deep learning", off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yo, I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'Yo, I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'Yo, I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'Yo, I love deep learning']],
      dtype=object)>

In [ ]:
#Creating examples of one hot tensors
car_list=tf.constant([0,1,2,3,4]) #represent each car brands

In [ ]:
depth=5
car_list.dtype

tf.int32

In [ ]:
car=tf.one_hot(car_list,depth)

In [ ]:
car

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
 tf.one_hot(car_list,depth=5,on_value="Car",off_value="No")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'Car', b'No', b'No', b'No', b'No'],
       [b'No', b'Car', b'No', b'No', b'No'],
       [b'No', b'No', b'Car', b'No', b'No'],
       [b'No', b'No', b'No', b'Car', b'No'],
       [b'No', b'No', b'No', b'No', b'Car']], dtype=object)>

### Some more mathematical operations

* Squaring element
* log of element
* Square root of element

In [ ]:
#create a new tensor
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
#Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#Find the square root
tf.math.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
#Find the log
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and Numpy
### Tensorflow interacts beautifully with numpy arrays

In [ ]:
# create a tensor directly from a NumPy array
J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
#Convert to numpy array
np.array(J),type(J)

(array([ 3.,  7., 10.]), tensorflow.python.framework.ops.EagerTensor)

In [ ]:
type(np.array(J))

numpy.ndarray

In [ ]:
#Convert tensor J to a numpy array
J.numpy(),type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J=tf.constant([2.0])

In [ ]:
J.numpy()[0]

2.0

In [ ]:
#Default types of each are slightly different
numpy_J=tf.constant(np.array([3.,7.,9.]))
tensor_J=tf.constant([3.,7.,8.])
#Check the datatypes of each
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

### Tensors and Numpy

Tensors interacts beautifully with numpy arrays.
🔑**Note**-One of the difference between a Tensorflow tensor and Numpy array is that a Tensorflow tensor can run on a GPU and TPU (for faster numerical processing)

### Finding access to GPUs

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sun Aug 20 10:07:54 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8    10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### Nevdia System Management Interface

🔑**Note** - If you have access to a CUDA-enabled GPU, Tensorflow will automatically use it whenever possible.   

🛠 00.Tensorflow Fundamentals Execrises

In [ ]:
## Create a vector ,scalar,matrix and tensor with values of choosing using tf.constant()
import tensorflow as tf
A=tf.constant([1,2,3,4,5])
A

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [ ]:
B=tf.constant([[1,2,3],
               [4,5,6],
               [7,8,9]])
B

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
import tensorflow as tf
C=tf.random.uniform(shape=(3,4),minval=10,maxval=100)
C

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[84.35472 , 20.264975, 20.485172, 81.829216],
       [96.16838 , 92.612305, 75.52959 , 28.788435],
       [10.669672, 99.3506  , 69.15996 , 64.01564 ]], dtype=float32)>

### Exercises

In [ ]:
scalar=tf.constant(4)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
scalar.ndim

0

In [ ]:
vector=tf.constant([1,2,3])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
vector.ndim


1

In [ ]:
matrix=tf.constant([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#Matrix islike box structure nX m or M X N but tensor is ndimensional arrays satisfying particular point.


In [ ]:
import tensorflow as tf
tensor = tf.constant([[[[1, 2, 3, 4],
                        [1, 2, 3, 4]],
                       [[1, 2, 3, 4],
                        [1, 2, 3, 4]]],
                      [[[1, 2, 3, 4],
                        [1, 2, 3, 4]],
                       [[1, 2, 3, 4],
                        [1, 2, 3, 4]]]])
tensor

<tf.Tensor: shape=(2, 2, 2, 4), dtype=int32, numpy=
array([[[[1, 2, 3, 4],
         [1, 2, 3, 4]],

        [[1, 2, 3, 4],
         [1, 2, 3, 4]]],


       [[[1, 2, 3, 4],
         [1, 2, 3, 4]],

        [[1, 2, 3, 4],
         [1, 2, 3, 4]]]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2, 2, 4])

In [ ]:
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=32>

In [ ]:
tensor.ndim # it tells the dimension of tensor which is ndimensional matrix

4

In [ ]:
tensor_1=tf.random.uniform(shape=(5,300),minval=0,maxval=1)

In [ ]:
tensor_1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.16988146, 0.7667053 , 0.4779588 , ..., 0.62271655, 0.84406316,
        0.51617825],
       [0.25025535, 0.98188186, 0.24495745, ..., 0.7785088 , 0.4225676 ,
        0.39394808],
       [0.90924   , 0.6367271 , 0.10749686, ..., 0.3622948 , 0.8526417 ,
        0.5057291 ],
       [0.72362065, 0.36156   , 0.3383546 , ..., 0.7924448 , 0.469777  ,
        0.80338085],
       [0.5830519 , 0.55345905, 0.8849629 , ..., 0.12368321, 0.36073124,
        0.5539067 ]], dtype=float32)>

In [ ]:
tensor_2=tf.random.uniform(shape=(5,300),minval=0,maxval=1)
tensor_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.69564295, 0.4414909 , 0.10425425, ..., 0.6780331 , 0.18645239,
        0.8263161 ],
       [0.2521572 , 0.28583884, 0.72158563, ..., 0.79046607, 0.22105622,
        0.6614462 ],
       [0.04821956, 0.86438096, 0.10870326, ..., 0.54237306, 0.3343966 ,
        0.4697243 ],
       [0.3565346 , 0.660033  , 0.15280879, ..., 0.6789013 , 0.7693392 ,
        0.06399798],
       [0.36522436, 0.49600816, 0.1148771 , ..., 0.99408555, 0.2989812 ,
        0.41067183]], dtype=float32)>

In [ ]:
#Scalar multiplication of 2 tensors
tensor_1*tensor_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.11817684, 0.3384934 , 0.04982923, ..., 0.42222244, 0.15737759,
        0.4265264 ],
       [0.06310369, 0.28065997, 0.17675777, ..., 0.61538476, 0.0934112 ,
        0.26057547],
       [0.04384315, 0.55037475, 0.01168526, ..., 0.19649893, 0.2851205 ,
        0.23755324],
       [0.2579958 , 0.23864152, 0.05170355, ..., 0.5379918 , 0.36141786,
        0.05141475],
       [0.21294476, 0.2745202 , 0.10166198, ..., 0.12295169, 0.10785186,
        0.22747387]], dtype=float32)>

In [ ]:
tf.matmul(tensor_1,tf.transpose(tensor_2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.719444, 70.87102 , 69.60451 , 74.4765  , 74.76798 ],
       [77.39395 , 72.61933 , 73.55038 , 79.73925 , 77.30463 ],
       [73.90178 , 73.25863 , 71.40186 , 80.39456 , 75.89474 ],
       [79.04227 , 76.781   , 74.27249 , 82.74442 , 80.43515 ],
       [71.135284, 73.253944, 69.18543 , 76.135445, 75.52162 ]],
      dtype=float32)>

In [ ]:
#Multiply two random tensors
# tf.tensordot(tensor_1,tensor_2,axes=1)
tf.rank(tensor_1),tf.rank(tensor_2)

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [ ]:
#Dot Product

tensor_2=tf.transpose(tensor_2)

In [ ]:
tensor_2

<tf.Tensor: shape=(300, 5), dtype=float32, numpy=
array([[0.69564295, 0.2521572 , 0.04821956, 0.3565346 , 0.36522436],
       [0.4414909 , 0.28583884, 0.86438096, 0.660033  , 0.49600816],
       [0.10425425, 0.72158563, 0.10870326, 0.15280879, 0.1148771 ],
       ...,
       [0.6780331 , 0.79046607, 0.54237306, 0.6789013 , 0.99408555],
       [0.18645239, 0.22105622, 0.3343966 , 0.7693392 , 0.2989812 ],
       [0.8263161 , 0.6614462 , 0.4697243 , 0.06399798, 0.41067183]],
      dtype=float32)>

In [ ]:
tf.tensordot(tensor_1,tensor_2,axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.719444, 70.87102 , 69.60451 , 74.4765  , 74.76798 ],
       [77.39395 , 72.61933 , 73.55038 , 79.73925 , 77.30463 ],
       [73.90178 , 73.25863 , 71.40186 , 80.39456 , 75.89474 ],
       [79.04227 , 76.781   , 74.27249 , 82.74442 , 80.43515 ],
       [71.135284, 73.253944, 69.18543 , 76.135445, 75.52162 ]],
      dtype=float32)>

In [ ]:
#Random tensor
tensor_3=tf.random.uniform(shape=(224,224,3),minval=0,maxval=100)
tensor_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[36.960102 , 72.194626 , 36.8837   ],
        [37.40598  , 51.633846 , 69.34096  ],
        [27.939426 , 42.268097 , 32.253204 ],
        ...,
        [96.4781   , 63.328266 , 11.284137 ],
        [ 9.714532 , 90.27549  , 54.243065 ],
        [ 7.6538086, 56.14592  , 45.1012   ]],

       [[64.16882  , 79.99172  , 48.773026 ],
        [71.62978  , 11.192536 , 32.1375   ],
        [75.814964 ,  8.060145 , 76.91112  ],
        ...,
        [27.93882  , 24.857557 , 61.640144 ],
        [47.577858 , 71.886955 , 97.20645  ],
        [18.006002 , 44.21582  , 67.25996  ]],

       [[ 2.3920655, 94.212135 , 48.998283 ],
        [88.29876  , 11.944378 , 17.338812 ],
        [60.581078 , 84.72636  , 40.302788 ],
        ...,
        [67.4114   , 84.39939  , 69.12573  ],
        [70.65178  , 71.08493  ,  6.3980103],
        [37.713158 , 68.64195  , 65.094795 ]],

       ...,

       [[ 1.8862844, 64.610275 , 42.477345 ],
        [32.0

In [ ]:
tf.reduce_max(tensor_3,axis=1)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[99.992195, 99.29094 , 98.08973 ],
       [99.44361 , 99.83457 , 99.86808 ],
       [99.65789 , 99.87842 , 99.293304],
       [99.53741 , 99.87247 , 98.76921 ],
       [99.87447 , 99.987366, 99.36331 ],
       [99.67255 , 99.90541 , 99.94439 ],
       [99.476074, 99.881454, 99.897385],
       [99.30754 , 99.63286 , 96.81498 ],
       [99.66985 , 99.27326 , 99.55305 ],
       [99.72699 , 99.34233 , 99.36007 ],
       [99.604416, 99.65454 , 99.952995],
       [99.049286, 99.52168 , 99.53507 ],
       [99.81467 , 99.975296, 99.76387 ],
       [99.08173 , 99.88444 , 99.98263 ],
       [99.45501 , 99.40431 , 99.859726],
       [99.72549 , 99.93339 , 99.59647 ],
       [99.82334 , 99.87227 , 99.52403 ],
       [99.061874, 99.766556, 99.58943 ],
       [99.51663 , 99.92483 , 99.95696 ],
       [99.97309 , 99.55012 , 99.75151 ],
       [99.260864, 99.73657 , 99.76453 ],
       [98.06898 , 99.99294 , 99.88035 ],
       [99.86545 , 99.7408

In [ ]:
tf.reduce_min(tensor_3,axis=0)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[2.64048576e-01, 3.44944000e-01, 8.82422924e-01],
       [5.52201271e-01, 3.76343727e-02, 1.70636177e-01],
       [8.27956200e-01, 2.52556801e-01, 2.35692263e+00],
       [2.14576721e-02, 1.98054314e-01, 3.07047367e-01],
       [1.13500357e+00, 7.90429115e-01, 2.22504139e-01],
       [4.49419022e-01, 1.84215307e+00, 5.27787209e-01],
       [1.48093700e-01, 3.00884247e-01, 1.11690760e+00],
       [3.47661972e-01, 2.12216377e-01, 4.61375713e-01],
       [6.11293316e-01, 4.31025028e-01, 8.50796700e-02],
       [1.41489506e-01, 3.73315811e-01, 6.16788864e-01],
       [1.21769905e+00, 1.35271549e+00, 3.78799438e-01],
       [3.06880474e-01, 1.56998634e-02, 4.91034985e-01],
       [3.28779221e-01, 2.63130665e-01, 4.43923473e-01],
       [4.93443012e-01, 2.44855881e-01, 1.33275986e-02],
       [2.69651413e-01, 5.52058220e-02, 1.11746788e+00],
       [1.23345852e+00, 2.55250931e-01, 3.29017639e-03],
       [3.80170345e-01, 1.26624107e-01

In [ ]:
#Create random tesnsor and then squeezed it
tensor_4=tf.random.uniform(shape=(1,224,224,3),minval=10,maxval=1000)

In [ ]:
tensor_4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[359.15128 , 118.434555, 680.42786 ],
         [269.5696  , 973.1793  , 596.64166 ],
         [855.5689  , 590.70337 , 412.984   ],
         ...,
         [715.0686  , 826.4529  , 194.56367 ],
         [940.9087  , 468.81274 , 742.5064  ],
         [576.9695  , 880.2319  ,  29.355175]],

        [[729.2852  , 229.22638 , 173.75087 ],
         [622.0431  , 845.91345 , 511.62006 ],
         [678.66516 , 311.00085 , 307.48004 ],
         ...,
         [ 62.511635,  18.771393,  18.449087],
         [587.5983  ,  84.25949 , 724.62256 ],
         [700.1912  , 498.43    , 580.0802  ]],

        [[571.0698  , 293.87054 ,  61.696487],
         [882.2198  , 883.5829  , 419.68878 ],
         [352.50525 , 737.9749  , 604.5003  ],
         ...,
         [443.55    , 378.4929  , 438.35428 ],
         [392.1293  , 210.8274  , 735.5223  ],
         [ 56.16113 , 409.52835 , 223.31053 ]],

        ...,

        [[824.0798  , 886.41364 , 

### tf.squeezed is used to remove size of dimension of tensorflow tensors


In [ ]:
tf.squeeze(tensor_3)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[36.960102 , 72.194626 , 36.8837   ],
        [37.40598  , 51.633846 , 69.34096  ],
        [27.939426 , 42.268097 , 32.253204 ],
        ...,
        [96.4781   , 63.328266 , 11.284137 ],
        [ 9.714532 , 90.27549  , 54.243065 ],
        [ 7.6538086, 56.14592  , 45.1012   ]],

       [[64.16882  , 79.99172  , 48.773026 ],
        [71.62978  , 11.192536 , 32.1375   ],
        [75.814964 ,  8.060145 , 76.91112  ],
        ...,
        [27.93882  , 24.857557 , 61.640144 ],
        [47.577858 , 71.886955 , 97.20645  ],
        [18.006002 , 44.21582  , 67.25996  ]],

       [[ 2.3920655, 94.212135 , 48.998283 ],
        [88.29876  , 11.944378 , 17.338812 ],
        [60.581078 , 84.72636  , 40.302788 ],
        ...,
        [67.4114   , 84.39939  , 69.12573  ],
        [70.65178  , 71.08493  ,  6.3980103],
        [37.713158 , 68.64195  , 65.094795 ]],

       ...,

       [[ 1.8862844, 64.610275 , 42.477345 ],
        [32.0

In [ ]:
### Tensor with random with shapes
tensor_5=tf.random.uniform(shape=[10],minval=10,maxval=100)
tensor_5

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([76.01085 , 11.135808, 47.15131 , 58.74901 , 98.02035 , 37.887733,
       88.90719 , 28.230652, 16.01717 , 12.938103], dtype=float32)>

### tf.argmax()-index of the max values of any tensor

In [ ]:
tf.argmax(tensor_5)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [ ]:
Numpy_A=tf.constant([0,2,3,4,5]) #car brands 0=BMW,1=Audi,2=Mercedes,3=lambo,4=toyota,5=ferrari
tf.one_hot(Numpy_A,depth=6)

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]], dtype=float32)>

### One-hot encoding is a common processing step in ml in which u convert categorical data into machine friendly codes.

### Tensorflow execrise completed
⚒00.Tensorflow Fundamentals execrises